<a href="https://colab.research.google.com/github/harshdsdh/deep-learning-with-pytorch/blob/master/basicsPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
a  =  torch.ones(3)

In [5]:
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [0]:
a[2] = 2.0

In [8]:
a

tensor([1., 1., 2.])

In [0]:
points = torch.tensor([[1.,4.],[2.,1.],[3.,5.]])

In [11]:
points[0]

tensor([1., 4.])

In [12]:
points.shape

torch.Size([3, 2])

In [13]:
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [14]:
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [0]:
  double_points = torch.ones(10, 2, dtype=torch.double)

In [17]:
double_points.dtype

torch.float64

In [18]:
points[1:]

tensor([[2., 1.],
        [3., 5.]])

In [0]:
l = list(range(9))

In [23]:
a = torch.tensor(l)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
b=a.view(3,3)
b[1,1]

tensor(4)

In [27]:
c  =  b[1:,1:]
c

tensor([[4, 5],
        [7, 8]])